### ISSUE TITLE
"state" attribute in "WithConfigMixin"

### ISSUE THREAD

**Issue by shaunc** [indexiatech/ember-idx-button#1]
"state" is an internal View property -- when the mixin gets mixed in, I get:

```
DEPRECATION: Usage of `state` is deprecated, use `_state` instead.
    at deprecate (http://0.0.0.0:4200/assets/vendor.js:26996:15)
    at defineProperty.get (http://0.0.0.0:4200/assets/vendor.js:27004:31)
    at replaceObserversAndListeners (http://0.0.0.0:4200/assets/vendor.js:29530:21)
    at applyMixin (http://0.0.0.0:4200/assets/vendor.js:29580:9)
    at MixinPrototype.applyPartial (http://0.0.0.0:4200/assets/vendor.js:29760:14)
    at Function.Class.proto (http://0.0.0.0:4200/assets/vendor.js:48081:32)
    at Function.Class.proto (http://0.0.0.0:4200/assets/vendor.js:48077:38)
    at EmberObject.create.helper (http://0.0.0.0:4200/assets/vendor.js:22522:34)
    at viewHelper (http://0.0.0.0:4200/assets/vendor.js:22781:25)
```

A different name would be better, even if it seems like "_state" will eventually become the name of the view property. As it is it may confuse rendering, though I haven't seen it doing so.

**Comment by lolmaus** [comment]
Ran into this issue too.
